# Site settings
title: Ptimulus
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Et si on envoyait un ballon dans la stratosph√®re ?
baseurl: "" # the subpath of the site
url: "http://ptimulus.eu" # the base hostname & protocol for the site
languages: ["fr"]
encoding: "utf-8"

category-list:
  - url: ptimulus1
    pretty: "Ptimulus 1"

permalink: none

# Build settings
markdown: kramdown
