# Site settings
title: Ptimulus
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Il se passe quoi si on envoit un ballon dans la stratosphère ?
baseurl: "" # the subpath of the site
url: "http://ptimulus.eu" # the base hostname & protocol for the site

category-list:
  - url: ptimulus1
    pretty: "Ptimulus 1"
  - url: regulation
    pretty: "Réglementation"

permalink: none

# Build settings
markdown: kramdown
